### ISSUE TITLE
bower support

### ISSUE THREAD

**Issue by vinaylakkam** [seanCodes/bootstrap-less-port#10]
Would you please provide bower support? Or let me know if there is tweak to do myself.

**Comment by seanCodes** [comment]
Hey @vinaylakkam. Yeah I can add Bower support. I originally held off since the Bower team seems to be encouraging users to migrate off of Bower. (There’s even a [blog post](https://bower.io/blog/2017/how-to-drop-bower-support/) with guidance for package maintainers on how to _drop_ support for Bower.)

I’d encourage you use npm or yarn, since both are faster and more secure, but if that's not a possibility then I can mind look into adding a bower config. (Or feel free to submit a pull request!)

**Comment by seanCodes** [comment]
Fixed by 3eef1e8
