### ISSUE TITLE
Problems with @plugin in Magento 2

### ISSUE THREAD

**Issue by Julime** [seanCodes/bootstrap-less-port#17]
I'm trying to use this in our Magento 2 e-commerce projects. 
While compiling less i get the following error: 
```
main.CRITICAL: ParseError: Unexpected input in _functions.less on line 5, column 1
3| // Utility mixins and functions for evaluating source code across our variables, maps, and mixins.
4| 
5| @plugin "plugins/index";
6| 
7| // LESS PORT: This plugin implements a function for returning a list of keys in a map, like Sass’
8| // [`map-keys()`](http://sass-lang.com/documentation/Sass/Script/Functions.html#map_keys-instance_method) [] []
```
Magento is using php to compile less:
https://github.com/oyejorge/less.php

Any Idea on how i can fix this?

**Comment by seanCodes** [comment]
Looking at the [less.php docs](https://github.com/oyejorge/less.php#about), it seems plugins (or what they call “custom functions” aren’t supported 😞:

>Please note, there are a few unsupported LESS features:
>
> - Evaluation of JavaScript expressions within back-ticks (for obvious reasons).
> - Definition of custom functions.

So unfortunately, the way to fix this would be to fork this port and swap out the custom functions with mixins, which is definitely possible, but would be tricky. It seems less.php is on a much lower version of Less (1.7.0), so certain syntax would have to be replaced as well.

[Older versions of this port](https://github.com/seanCodes/bootstrap-less-port/tree/v0.0.3) used mixins in place of some plugins (the breakpoint functions) and used older syntax as well, so you could try checking that out.

If I get some time I’ll try messing around with making a compatible version since it seems like this could be a common use case, but no promises. 😅

**Comment by mageho** [comment]
Good morning,

I am using this module purposely for a Magento 2 website.

I did not remember the whole step to using plugins, but I remember Magento search in different paths for module, and I was forced to create a symbolic link in the root path of Magento to 
/lib/web/npm-asset/bootstrap-less-port/less/plugins

You can take a look especially to https://github.com/SnowdogApps/magento2-theme-blank-sass and https://github.com/SnowdogApps/magento2-frontools which create symbolic link to access vendor version.

It gives you small hints how to do it,

Ilan
