### ISSUE TITLE
Is there any update for 4.5.x

### ISSUE THREAD

**Issue by ThemeMetro** [seanCodes/bootstrap-less-port#28]
Hello,

Is there any update for bootstrap 4.5.x

**Comment by seanCodes** [comment]
Yes! Just had a baby recently and got really busy. I'll update as soon as I can, hopefully this weekend.

**Comment by ThemeMetro** [comment]
> Yes! Just had a baby recently and got really busy. I'll update as soon as I can, hopefully this weekend.

Congratulation!! and Thank you very much :)

**Comment by ThemeMetro** [comment]
> Yes! Just had a baby recently and got really busy. I'll update as soon as I can, hopefully this weekend.

Is there any update?

**Comment by seanCodes** [comment]
@ThemeMetro had to fix a few things first, but yes, all up to date now. A version of this port has been published for each Bootstrap version since 4.3.1. The latest 4.6.0 (`bootstrap-less-port@^2.5.0`), but if you need Bootstrap 4.5 then install `bootstrap-less-port@^2.4.3`. For more info see the [changelog](https://github.com/seanCodes/bootstrap-less-port/blob/master/CHANGELOG.md).
